### ISSUE TITLE
Set up start website for metafacture.org

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture.github.io#15]
At the moment www.metafacture.org refers straight the metafacture-documentation repo and it links to all of the scattered documentation. Since we already have a basic website for the ide-extension we also should also get a new start page that leads to the different parts of the documentation:

User groups should be:
 - metafacture and morph users
 - advanced users that also want to programm new features
 - programmers that want to maintain/contribute to metafacture

**Comment by katauber** [comment]
We should begin with the start page (published to github pages) and add a link to the ide-extensions subpage and to the metafacture blog in this ticket. The documentation for the different user groups can be added later.
And the url metafacture.org should not redirect to https://github.com/metafacture/metafacture-documentation anymore but there should be a reverse proxy.

Functional review:
Code review:

**Comment by katauber** [comment]
The Github Pages site is currently being built from the 15-addStartPage branch, so this ticket can be reviewed on [metafacture.org](metafacture.org).
Should we already add some more content? If yes, which?

**Comment by katauber** [comment]
> Cool more content :)
> 
> Some more thing I saw:
> 
> 1. The pipes in the navigation are not consistent, there are different pipes used blue and black.

✔️ 
> 2. I still think that the navigation would look better if centered and the links to the different contents would not be as narrow as they are now.

✔️ 
> 3. The metafacture title and the header are redundant, I would prefer to delet the metafacture title and straight start with "Welcome".

✔️ 
> 4. Anyway to integrate the blog straigt in the website?

I think in this simple implementation with pandoc that's not (that easy) possible
> 5. I would not use Twitter in the navigation, but somewhere with an Icon. Perhaps besides the github link with an icon. But idk.

I removed the Twitter link now. Should I add the github and twitter link on a new page?

**Comment by TobiasNx** [comment]
I like how it looks now! :)

> > 1. Anyway to integrate the blog straigt in the website?
> 
> I think in this simple implementation with pandoc that's not (that easy) possible

Okay, fair enough!

> 
> > 1. I would not use Twitter in the navigation, but somewhere with an Icon. Perhaps besides the github link with an icon. But idk.
> 
> I removed the Twitter link now. Should I add the github and twitter link on a new page?

Wouldn't just adding a Twitter and a Github Icon in the upper right corner. Or perhaps at the end of the navigation bar? But I do not know a perfect solution :) 

Additional point:
I also saw that the tab of the site jusst shows "Welcome" with no icon and no refrence to Metafacture:
![grafik](https://user-images.githubusercontent.com/61879957/140035731-c1e4d7b1-5bec-497c-a5d0-6f30f3516299.png)

**Comment by katauber** [comment]
> Wouldn't just adding a Twitter and a Github Icon in the upper right corner. Or perhaps at the end of the navigation bar? But I do not know a perfect solution :)

Please check if you like it now :)

> 
> Additional point: I also saw that the tab of the site jusst shows "Welcome" with no icon and no refrence to Metafacture

✔️

**Comment by TobiasNx** [comment]
+ 1 cool :)
