### ISSUE TITLE
Set up /extensions landing page

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture.github.io#2]
To be running on on https://metafacture.org/extensions:

- Overview of the extensions
- Setup instructions for flux and fix extensions
- Mini tutorial: first flux, then fix

Will be deployed using `index.html` in `/extensions`.

We should maintain the content as a `*.md` file.

**Comment by katauber** [comment]
To review please visit https://metafacture.github.io/extensions/ @acka47

**Comment by acka47** [comment]
Looks good, I only have one suggestion for adding to the content, see #4.

Otherwise, some styling/CSS would probably do the page some good.

**Comment by fsteeg** [comment]
@dr0i: As discussed in the standup, https://metafacture.org/extensions should remain in the browser adress bar (not redirect to https://metafacture.github.io/extensions/, needs reverse proxy?)

**Comment by katauber** [comment]
@acka47 Added CSS for extensions landing page.

**Comment by acka47** [comment]
> Added CSS for extensions landing page.

Looks good. Thanks! Closing.

**Comment by dr0i** [comment]
Added to a vhost metafacture.org.conf:

> ProxyPass / https://metafacture.github.io/
ProxyPassReverse / https://metafacture.github.io/

Restarted webserver. Check https://metafacture.github.io/extensions/ .

**Comment by acka47** [comment]
You mean to check https://metafacture.org/extensions/ I guess. Looks good.

**Comment by acka47** [comment]
Closing
